name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.1'
        cabal-version: '3.0'
        stack-version: '2.3.3' 
    - name: Build
      run: stack install
    - name: Run tests
      run: stack test
